### PR TITLE
feat: Temporarily show button for selected dashboard query

### LINKED ISSUE #720: Use an Indicator when using a Dashboard query on the Search tab
On the desktop, you are shown 6 advisories via a predefined query. Seeing more advisories of that query requires you to press a button below the query-column that opens the query on the search page. However, there's no indicator on the search page that this happened and that you're seeing a filtered and thus possibly reduced amount of advisories. Such an indicator should be added.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #720

### CODE REVIEW

**Review by cintek — CHANGES_REQUESTED** [review]
It is working that the opened queries are visible in Search but there is one problem:

- Login as editor
- click on the button below the **event** queries
more-button
- select "Documents"
opened-dashboard-query

Result:
opened-dashboard-query-error

**Comment by luisa-beerboom** [comment]
@cintek can't replicate this. Do you have an up-to-date backend?

**Comment by luisa-beerboom** [comment]
The client is calling with the route `api/documents?query=$state new workflow =&advisories=false&count=1&orders=-critical&limit=10&offset=0&columns=critical cvss_v3_score cvss_v2_score ssvc four_cves publisher title tracking_id initial_release_date current_release_date version comments id`
IDK why that causes an error, I'm not really knowledgable about the query request syntax.
@s-l-teichmann What do you think?

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM
The issue described by @cintek is indeed in main as well and now tracked by
https://github.com/ISDuBA/ISDuBA/issues/752

**Review by cintek — APPROVED** [review]
Works

**Pull request merged**
