### PR TITLE
Allow to specify multiple order levels

### LINKED ISSUE #302: Query Designer: Add the possibilty to add more than one order criterion
The UI currently offers only the possibility to give one order criterion. This is to coarse:
Assume sorting by `critical` resulting in a list of entries which all have same value.
In this case you may want the more recently updated advisories/documents appear in the front of that list.

The backend already supports this.

### PR DESCRIPTION
**Pull request by koplas**
Closes #302

### CODE REVIEW

**Comment by cintek** [comment]
The UI for selecting the order looks a bit unordinary. When using an indicator (like [Vuetify does](https://vuetifyjs.com/en/components/data-tables/data-and-display/#multi-sort)) for the order of the order we would only need one column.

**Comment by s-l-teichmann** [comment]
> The UI for selecting the order looks a bit unordinary. When using an indicator (like [Vuetify does](https://vuetifyjs.com/en/components/data-tables/data-and-display/#multi-sort)) for the order of the order we would only need one column.

This not true ... Think the dashbord where we have only 6 cards. Selecting only the first 6 items with on column order criterion will bring up other results has having more than one right from the start.

**Comment by cintek** [comment]
> This not true ... Think the dashbord where we have only 6 cards. Selecting only the first 6 items with one column order criterion will bring up other results has having more than one right from the start.

Sorry, I didn't make my point clear enough. I meant the columns in the UI used to display the order:
order

**Review by cintek — APPROVED** [review]
LGTM & works

**Pull request merged**
