### PR TITLE
Only enable save if source is different

### LINKED ISSUE #374: Source management: Enable save button only if there really is a change
If you change a source and revert the change the save button is still active although the final options do not differ from the old options.

### PR DESCRIPTION
**Pull request by koplas**
Closes #374

### CODE REVIEW

**Comment by JanHoefelmeyer** [comment]
Source considers itself changed if an empty ignore pattern is added. (I think that's not really an issue though)
Otherwise, LGTM & works

**Comment by cintek** [comment]
@koplas can you please solve the conflicts?

**Review by cintek — APPROVED** [review]
LGTM

**Review by cintek — CHANGES_REQUESTED** [review]
Does not work for e.g. `rate` or `insecure`. Probably because the initial value is undefined or null but when you select and deselect a checkbox or enter a character and remove it from an input the new value is `false` or an empty string.

**Comment by koplas** [comment]
> Does not work for e.g. `rate` or `insecure`. Probably because the initial value is undefined or null but when you select and deselect a checkbox or enter a character and remove it from an input the new value is `false` or an empty string.

Does this still happen if you create a new source?

**Comment by cintek** [comment]
> Does this still happen if you create a new source?

Yes.

Object before change:
```
{"id":3,"name":"Red Hat Product Security","url":"redhat.com","active":false,"rate":1,"slots":2,"strict_mode":true,"stats":{"downloading":0,"waiting":0},"ignore_patterns":[""]}
```

Object after I checked `insecure`:
```
{"id":3,"name":"Red Hat Product Security","url":"redhat.com","active":false,"rate":1,"slots":2,"strict_mode":true,"stats":{"downloading":0,"waiting":0},"ignore_patterns":[""],"insecure":true,"headers":[]}
```

Object after I unchecked `insecure`:
```
{"id":3,"name":"Red Hat Product Security","url":"redhat.com","active":false,"rate":1,"slots":2,"strict_mode":true,"stats":{"downloading":0,"waiting":0},"ignore_patterns":[""],"insecure":false,"headers":[]}
```

**Review by cintek — APPROVED** [review]
LGTM & works

**Pull request merged**
