### PR TITLE
feat: Move aggregator add form to modal

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Old location below the list made it look like an afterthought and didn't quite fit in visually.
It also made the purpose of the aggregator viewer confusing, as it held both the function of a general overview and a create view at once.

With the modal the 'add' functionality is now separated from the overview.
The button is also placed in a prominent place right beside the view-title,
ensuring that no scrolling and searching is needed to find it, no matter how long the list is.

### CODE REVIEW

**Review by koplas — APPROVED** [review]
LGTM & works

**Comment by koplas** [comment]
@luisa-beerboom Can you resolve the merge conflicts?

**Comment by s-l-teichmann** [comment]
As the word 'modal' is part of the title you'd better check this with @bernhardreiter first before you merge it.

**Comment by bernhardreiter** [comment]
It most likely shouldn't be really "modal". 

Is this adding funcationality consistent with other adding functions in the application?

**Comment by luisa-beerboom** [comment]
@bernhardreiter let's talk about it

**Pull request closed without merging**
