### PR TITLE
Allow users to compare different advisories

### LINKED ISSUE #120: Diff: Compare documents from different advisories
Implement a feature so that users can compare random documents.

### PR DESCRIPTION
**Pull request by cintek**
Resolves #120 and #121 

TODO:
- [x] Add a first version of a feature that allows users to select different documents and compare them
- [x] Prepare backend so users can upload a document for a diff
- [x] Let users upload a document for diff in the client
- [x] Remove Git diff components
- [x] Remove `Compare` from sidebar
- [x] Refactor, e.g. rename diff components as there is no need to differ between components for the git and the JSON diff

### CODE REVIEW

**Comment by cintek** [comment]
@s-l-teichmann I added you to the assignes 'cause the backend shall offer the temporary upload of documents for a diff.

**Comment by s-l-teichmann** [comment]
@cintek PR #207 provides the needed backend infrastructure.

**Comment by cintek** [comment]
@JanHoefelmeyer can you please test the following things:

- Compare different versions of the same advisory (was implemented before this PR but I had to change a few things there so another test is necessary)
- Compare different advisories/documents from `Search`
- Upload documents (no import) and compare them with each other and with other advisories/documents

**Review by JanHoefelmeyer — APPROVED** [review]
Functionally works. UI may need further refinements, but within later iterations/after more discussion

**Comment by cintek** [comment]
Thanks for testing! What I forgot in the TODO list is testing the configuration (settings expiration limit etc.). Can you please also test that?

**Pull request merged**
