### PR TITLE
Finer rework of advisory

### PR DESCRIPTION
**Pull request by luisa-beerboom**
see #488

### CODE REVIEW

**Comment by luisa-beerboom** [comment]
TODO (among others): 

- [ ] Replace current cutoffs with more sensible ones
- [ ] Many products cause the vulnerabilities overview to increase loading time by a lot. Change that somehow. This has already been fixed for the many CVEs case via the show all button, but the products still have to be considered.

**Review by JanHoefelmeyer — CHANGES_REQUESTED** [review]
Uncaught (in promise) Error: {#each} only works with iterable values.
    ensure_array_like_dev dev.js:218
    update ValueList.svelte:210
    update_slot_base utils.js:203
    update flowbite-svelte.js:76031
    update flowbite-svelte.js:76153
    update scheduler.js:119
    flush scheduler.js:79
    promise callback*schedule_update scheduler.js:20
    make_dirty Component.js:81
    ctx Component.js:139
    loadDocument Advisory.svelte:1554
    loadData Advisory.svelte:264
    update Advisory.svelte:305
    init Component.js:144
    Advisory Advisory.svelte:1983
    createProxiedComponent svelte-hooks.js:341
    ProxyComponent proxy.js:242
    Proxy<Advisory> proxy.js:349
    construct_svelte_component_dev dev.js:257
    create_if_block svelte-spa-router.js:219
    update svelte-spa-router.js:350
    update scheduler.js:119
    flush scheduler.js:79
    promise callback*schedule_update scheduler.js:20
    make_dirty Component.js:81
    ctx Component.js:139
    unsubscribeLoc svelte-spa-router.js:682
    subscribe2 index.js:84
    instance Router.svelte:481
    init Component.js:135
    Router svelte-spa-router.js:796
    create_if_block +page.svelte:67
    update +page.svelte:194
    update scheduler.js:119
    flush scheduler.js:79
    promise callback*schedule_update scheduler.js:20
    make_dirty Component.js:81
    ctx Component.js:139
    instance +page.svelte:254
    set index.js:56
dev.js:218:8

when trying to open BSI-2022-0003 

Please look into that, it causes the entire application to become unresponsive. (Current main does not run into that problem)

**Comment by luisa-beerboom** [comment]
@JanHoefelmeyer done.
Also made a change to the result rows in the search page, as it had been bothering me (while replicating the bug and in general), that the search result rows on the search page were organized so that the result would be visualized as an inline string in the cve column, potentially stretching it extremely wide and pushing the data from the columns on the right out of the screen.
So the result row content takes up the entire row now.

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
