### PR TITLE
Advisory comments recent

### PR DESCRIPTION
**Pull request by s-l-teichmann**
This PR adds two new columns to adviories:

- `comments`: Number of comments on this advisory
- `recent`: Time of the last recent event on this advisory.
- `versions`: Number of versions of this advisory.

### CODE REVIEW

**Comment by s-l-teichmann** [comment]
@ThomasJunk Mind to add the new columns `comments` and `recent` to the query builder and the results. They should only be available in advisory mode.

**Comment by ThomasJunk** [comment]
LGTM & works

**Review by ThomasJunk — APPROVED** [review]
LGTM

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
