### PR TITLE
Change word diff to JSON segmentation.

### PR DESCRIPTION
**Pull request by s-l-teichmann**
Solves #172

### CODE REVIEW

**Comment by s-l-teichmann** [comment]
@cintek Please add the client part

**Comment by cintek** [comment]
@s-l-teichmann in general it is working but I observed that sometimes I get a JSON object like this:
```
{
  op: "replace",
  path: "/vulnerabilities/0/scores/0/cvss_v3/baseScore",
  value: 7.8
}
```

I saw this two times with the `baseScore`. Everything else seems to work as expected. I thought the problem is that it is a number but on the other hand if `document/tracking/version` or `/document/tracking/generator/engine/version` changed the value of the object is correct.

**Comment by s-l-teichmann** [comment]
> @s-l-teichmann in general it is working but I observed that sometimes I get a JSON object like this:
> 
> ```
> {
>   op: "replace",
>   path: "/vulnerabilities/0/scores/0/cvss_v3/baseScore",
>   value: 7.8
> }
> ```
> 
> I saw this two times with the `baseScore`. Everything else seems to work as expected. I thought the problem is that it is a number but on the other hand if `document/tracking/version` or `/document/tracking/generator/engine/version` changed the value of the object is correct.

This is out of focus for this issue. The word-diff logic is only applied to text fields.

**Comment by cintek** [comment]
@JanHoefelmeyer can you please test the JSON diff component?

**Comment by JanHoefelmeyer** [comment]
LGTM & works

**Pull request merged**
