### PR TITLE
Refactor table

### PR DESCRIPTION
**Pull request by koplas**
This reduces code duplication and allows to change the displayed columns dynamically.

### CODE REVIEW

**Review by cintek — CHANGES_REQUESTED** [review]
Overall, this works and looks good. Thanks. There are only minor issues:

1. `savePosition` can be found very often in the code. I think it would be better to watch `offset`, `currentPage`, `limit` and `orderBy` and when they change automatically call `savePosition`
2. Now, if the user enters a letter in the search bar the application starts a request right away. Here it would be better to use a small delay and then start the request. If the user changes the input within the delay you would reset the "countdown". Then, we would reduce the amount of requests that have to be handled by the server.

**Comment by koplas** [comment]
> If you enter some characters in the search bar so that the number of result becomes smaller and then mark all characters and delete them there is no new request so the list won't be updated.

Done

**Review by cintek — APPROVED** [review]
Thanks!

**Comment by bernhardreiter** [comment]
Nitpicking the title: 

> and allows to change the displayed columns dynamically.

makes it something else than a "code refactoring", as this is
"the process of restructuring existing computer code [..] without changing its external behavior"
(cited from wikipedia). >;)

**Pull request merged**
