### PR TITLE
Only load events if allowed

### LINKED ISSUE #240: Error message on front page for roles that are not allowed to view recent events
This affects Admins and Importer.

### PR DESCRIPTION
**Pull request by koplas**
Closes #240

### CODE REVIEW

**Review by JanHoefelmeyer — APPROVED** [review]
This works, but other roles likely also want to have a recent activity feed if they are involved with advisories. (E.g. pinging admins for info)

So instead of just disabling the view, we might want to give access to events instead.

**Comment by JanHoefelmeyer** [comment]
Admin is not the only one affected, Importer as well.

Also now pinging admins will alert them on the homepage, but it will lead to an error (not allowed to see comments.)

Lastly, they'd need to be able to see comments for this to be worth it, which has some heavier implications.

**Comment by koplas** [comment]
> Admin is not the only one affected, Importer as well.

The importer role is intended for uploads only.

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
