### PR TITLE
feat: Use fixed width cve column in advisory table

### LINKED ISSUE #108: UI:  Fix position of components with parts with variable length
When browsing the Home, Advisories or Documents tab, a lot of components adjust their position depending on the length of the longest titles, which itself stretches the title column of the advisories overview. Examples are the pagination or the rest of the table. 

https://github.com/ISDuBA/ISDuBA/issues/50 is part of this issue.

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #108

### CODE REVIEW

**Review by JanHoefelmeyer — CHANGES_REQUESTED** [review]
Still jumping around for me:
image

image

image

**Comment by luisa-beerboom** [comment]
@koplas ping

**Comment by koplas** [comment]
I unassigned myself. @JanHoefelmeyer can give better input on this pull request.

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
