### PR TITLE
feat: Use human-readable datetime formats in advisory

### LINKED ISSUE #691: Human readable datetime format

### PR DESCRIPTION
**Pull request by luisa-beerboom**
Closes #691

### CODE REVIEW

**Review by koplas — DISMISSED** [review]
LGTM & works

**Comment by luisa-beerboom** [comment]
> It is probably best to not localize the time (as it makes it harder to compare).
> 
> A short format like `2024-11-26 21:00Z' would be cool if the rest is zeros anyway.

@bernhardreiter is this better?

**Review by koplas — APPROVED** [review]
LGTM & works

**Review by JanHoefelmeyer — APPROVED** [review]
LGTM & works

**Pull request merged**
