### PR TITLE
Expose keep_feed_logs configuration to client

### PR DESCRIPTION
**Pull request by koplas**

### CODE REVIEW

**Review by s-l-teichmann — CHANGES_REQUESTED** [review]
It seems a bit unmotivated here.

**Comment by koplas** [comment]
This was based on a request from @cintek. @cintek can you explain the motivation?

**Comment by cintek** [comment]
@JanHoefelmeyer suggested using the value of `keep_feed_logs` to pre-fill the `from` date where the feed logs are so we don't have date inputs which are just showing the placeholder.

**Comment by JanHoefelmeyer** [comment]
This shouldn't be done without a new explaining comment via the defaultMessage function but in a proper place with proper explanation

**Pull request closed without merging**
